version: "3.8"

services:
  app:
    build: .
    ports:
      - "8123:8123"
    volumes:
      - ./data:/app/data
      - ./web:/app/web
      - ./prompts:/app/prompts
      - /usr/local/bin/pandoc:/usr/local/bin/pandoc:ro
    env_file:
      - .env
